# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{opinionated-xml}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Zumwalt"]
  s.date = %q{2010-05-16}
  s.description = %q{A library to help you tame sprawling XML schemas like MODS.  Wraps Nokogiri documents in objects with miscellaneous helper methods for doing things like retrieve generated xpath queries or look up properties based on a simplified DSL}
  s.email = %q{matt.zumwalt@yourmediashelf.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "History.textile",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/opinionated-xml.rb",
     "lib/opinionated-xml/ox.rb",
     "lib/opinionated-xml/ox_property_values_helper.rb",
     "opinionated-xml.gemspec",
     "spec/fixtures/CBF_MODS/ARS0025_016.xml",
     "spec/fixtures/mods-3-2.xsd",
     "spec/fixtures/test_dummy_mods.xml",
     "spec/helpers/ox_property_values_helper_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/unit/opinionated-xml_spec.rb",
     "spec/unit/ox_integration_spec.rb"
  ]
  s.homepage = %q{http://github.com/mediashelf/opinionated-xml}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A library to help you tame sprawling XML schemas like MODS.}
  s.test_files = [
    "spec/helpers/ox_property_values_helper_spec.rb",
     "spec/spec_helper.rb",
     "spec/unit/opinionated-xml_spec.rb",
     "spec/unit/ox_integration_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<facets>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<mocha>, [">= 0.9.8"])
      s.add_development_dependency(%q<ruby-debug>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<facets>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<mocha>, [">= 0.9.8"])
      s.add_dependency(%q<ruby-debug>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<facets>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<mocha>, [">= 0.9.8"])
    s.add_dependency(%q<ruby-debug>, [">= 0"])
  end
end

